#pragma once
#include "driver/gpio.h"

/* HXESP4848AI0210DIC-A: ST7701S, 480x480, 3-wire SPI control + RGB565. */
#define BOARD_LCD_H_RES 480
#define BOARD_LCD_V_RES 480
#define BOARD_LCD_SPI_CS GPIO_NUM_39
#define BOARD_LCD_SPI_SCLK GPIO_NUM_2
#define BOARD_LCD_SPI_SDA GPIO_NUM_1
#define BOARD_LCD_RGB_PCLK GPIO_NUM_21
#define BOARD_LCD_RGB_HSYNC GPIO_NUM_16
#define BOARD_LCD_RGB_VSYNC GPIO_NUM_17
#define BOARD_LCD_RGB_DE GPIO_NUM_18
#define BOARD_LCD_RGB_DATA0 GPIO_NUM_15
#define BOARD_LCD_RGB_DATA1 GPIO_NUM_4
#define BOARD_LCD_RGB_DATA2 GPIO_NUM_5
#define BOARD_LCD_RGB_DATA3 GPIO_NUM_6
#define BOARD_LCD_RGB_DATA4 GPIO_NUM_7
#define BOARD_LCD_RGB_DATA5 GPIO_NUM_8
#define BOARD_LCD_RGB_DATA6 GPIO_NUM_47
#define BOARD_LCD_RGB_DATA7 GPIO_NUM_48
#define BOARD_LCD_RGB_DATA8 GPIO_NUM_46
#define BOARD_LCD_RGB_DATA9 GPIO_NUM_9
#define BOARD_LCD_RGB_DATA10 GPIO_NUM_10
#define BOARD_LCD_RGB_DATA11 GPIO_NUM_0
#define BOARD_LCD_RGB_DATA12 GPIO_NUM_11
#define BOARD_LCD_RGB_DATA13 GPIO_NUM_12
#define BOARD_LCD_RGB_DATA14 GPIO_NUM_13
#define BOARD_LCD_RGB_DATA15 GPIO_NUM_14
#define BOARD_LCD_BACKLIGHT_EN GPIO_NUM_NC /* BL_EN is driven by TCA9554 P2 */
#define BOARD_LCD_BACKLIGHT_PWM GPIO_NUM_38 /* BL_PWM: active low */
#define BOARD_LCD_BACKLIGHT_PWM_ON_LEVEL 0
#define BOARD_LCD_BACKLIGHT_PWM_OFF_LEVEL 1
#define BOARD_LCD_EXPANDER_ADDR 0x20
#define BOARD_LCD_EXPANDER_RESET_BIT (1u << 0)
#define BOARD_TOUCH_RST_EXPANDER_BIT (1u << 1) /* Extend_IO2 = P1 */
#define BOARD_LCD_BACKLIGHT_EN_EXPANDER_BIT (1u << 2) /* BL_EN: Extend_IO3 = P2, active high */
#define BOARD_LCD_BACKLIGHT_EN_ON_LEVEL 1
#define BOARD_LCD_BACKLIGHT_EN_OFF_LEVEL 0
#define BOARD_TOUCH_SDA GPIO_NUM_41
#define BOARD_TOUCH_SCL GPIO_NUM_40
#define BOARD_TOUCH_INT GPIO_NUM_45 /* TP_INT */
#define BOARD_TOUCH_RST GPIO_NUM_NC
