#pragma once
#include "driver/gpio.h"

/* HXESP4848AI0210DIC-A: ST7701S, 480x480, 3-wire SPI control + RGB565. */
#define BOARD_LCD_H_RES 480
#define BOARD_LCD_V_RES 480
#define BOARD_LCD_SPI_CS GPIO_NUM_39
#define BOARD_LCD_SPI_SCLK GPIO_NUM_2
#define BOARD_LCD_SPI_SDA GPIO_NUM_1
#define BOARD_LCD_RGB_PCLK GPIO_NUM_21
#define BOARD_LCD_RGB_HSYNC GPIO_NUM_16
#define BOARD_LCD_RGB_VSYNC GPIO_NUM_17
#define BOARD_LCD_RGB_DE GPIO_NUM_18
#define BOARD_LCD_RGB_DATA0 GPIO_NUM_15  /* B0 */
#define BOARD_LCD_RGB_DATA1 GPIO_NUM_4   /* B1 */
#define BOARD_LCD_RGB_DATA2 GPIO_NUM_5   /* B2 */
#define BOARD_LCD_RGB_DATA3 GPIO_NUM_6   /* B3 */
#define BOARD_LCD_RGB_DATA4 GPIO_NUM_7   /* B4 */
#define BOARD_LCD_RGB_DATA5 GPIO_NUM_8   /* G0 */
#define BOARD_LCD_RGB_DATA6 GPIO_NUM_47  /* G1 */
#define BOARD_LCD_RGB_DATA7 GPIO_NUM_48  /* G2 */
#define BOARD_LCD_RGB_DATA8 GPIO_NUM_46  /* G3 */
#define BOARD_LCD_RGB_DATA9 GPIO_NUM_9   /* G4 */
#define BOARD_LCD_RGB_DATA10 GPIO_NUM_10 /* G5 */
#define BOARD_LCD_RGB_DATA11 GPIO_NUM_0  /* R0 */
#define BOARD_LCD_RGB_DATA12 GPIO_NUM_11 /* R1 */
#define BOARD_LCD_RGB_DATA13 GPIO_NUM_12 /* R2 */
#define BOARD_LCD_RGB_DATA14 GPIO_NUM_13 /* R3 */
#define BOARD_LCD_RGB_DATA15 GPIO_NUM_14 /* R4 */
#define BOARD_LCD_BACKLIGHT_EN GPIO_NUM_NC /* BL_EN is driven by TCA9554 P2 */
#define BOARD_LCD_BACKLIGHT_PWM GPIO_NUM_38 /* BL_PWM: active low */
#define BOARD_LCD_BACKLIGHT_PWM_ON_LEVEL 0
#define BOARD_LCD_BACKLIGHT_PWM_OFF_LEVEL 1
#define BOARD_LCD_EXPANDER_ADDR 0x20
#define BOARD_LCD_EXPANDER_RESET_BIT (1u << 0)
#define BOARD_TOUCH_RST_EXPANDER_BIT (1u << 1) /* Extend_IO2 = P1 */
#define BOARD_LCD_BACKLIGHT_EN_EXPANDER_BIT (1u << 2) /* BL_EN: Extend_IO3 = P2, active high */
#define BOARD_LCD_BACKLIGHT_EN_ON_LEVEL 1
#define BOARD_LCD_BACKLIGHT_EN_OFF_LEVEL 0
#define BOARD_TOUCH_INT_ACTIVE_LOW 1
#define BOARD_TOUCH_I2C_ADDR_PRIMARY 0x5D
#define BOARD_TOUCH_I2C_ADDR_SECONDARY 0x14
#define BOARD_TOUCH_SDA GPIO_NUM_41
#define BOARD_TOUCH_SCL GPIO_NUM_40
#define BOARD_TOUCH_INT GPIO_NUM_45 /* TP_INT */
#define BOARD_TOUCH_RST GPIO_NUM_NC

/* Micro-SD socket: SDIO 1-bit signals from the schematic. */
#define BOARD_SD_CMD GPIO_NUM_1
#define BOARD_SD_CLK GPIO_NUM_2
#define BOARD_SD_D0 GPIO_NUM_42
